<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>PUFF SEMS forberedelse – Normalfordelingen</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Normalfordelingen</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="hvad-er-en-sandsynlighedsfordeling" class="slide level2">
<h2>Hvad er en sandsynlighedsfordeling?</h2>
<div class="columns">
<div class="column">
<p>Når vi måler når får vi som regel en række forskellige resultater.</p>
<p>Højde af mænd er et eksempel. Nogen er 1,85 meter. Andre 1,80 meter.</p>
<p>Når vi laver et histogram af alle de målinger, kunne det se således ud:</p>
</div><div class="column">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="normalfordelingen_files/figure-revealjs/hist-male-height-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Hvad er mest sandsynligt - at være mellem 190 og 195 cm eller at være mellem 180 og 185 cm høj</p>
</div></div>
</section>
<section id="hvad-er-normalfordelingen" class="slide level2">
<h2>Hvad er normalfordelingen?</h2>
<p>De målinger følger en sandsynlighedsfordeling.</p>
<p>Der findes mange forskellige sandsynlighedsfordelinger.</p>
<p>Når vi måler mange forskellige ting. Og undersøger hvilke sandsynlighedsfordelinger de følger. Så er den hyppigst forekommende “normalfordelingen”</p>
<aside class="notes">
<p>Det er ikke en normativ betegnelse, normal i denne kontekst blot den hyppigst forekommended</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hvordan-ser-den-ud" class="slide level2">
<h2>Hvordan ser den ud?</h2>
<p>Observationer der er normalfordelte følger denne fordeling:</p>
<p><span class="math display">\[
f(x) = \frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}
\]</span></p>
<p><span class="math inline">\(f(x)\)</span> er sandsynligheden for at se en observation med værdien x.</p>
<p><span class="math inline">\(\mu\)</span> er gennemsnittet af alle observationerne</p>
<p><span class="math inline">\(\sigma\)</span> er standardafvigelsen af alle observationerne.</p>
<p>Det er der jo ingen der orker at arbejde med…</p>
</section>
<section id="hvordan-ser-den-ud-1" class="slide level2">
<h2>Hvordan ser den ud?</h2>

<img data-src="normalfordelingen_files/figure-revealjs/normalfordelingen-1.png" width="960" class="r-stretch"><p>Her har vi målinger der kan gå fra -4 til 4. Og har <span class="math inline">\(\mu = 0\)</span> og <span class="math inline">\(\sigma = 1\)</span>. Arealet under kurven er 1 ~ 100%.</p>
<p>For alle værdierne er med og sandsynligheden for at vi ser en værdi er 100%</p>
</section>
<section id="hvilke-egenskaber-har-den" class="slide level2">
<h2>Hvilke egenskaber har den?</h2>
<p>Hvis vi har målinger/observationer af et eller andet, kan det være nyttigt at kunne svare på:</p>
<ol type="1">
<li>Hvor mange procent af observationerne er under 0.4?</li>
<li>Hvor mange procent af observationerne ligger mellem -2 og 2?</li>
<li>De 65.5% mindste observationer; hvad er de mindre end?</li>
<li>Indenfor hvilket interval ligger 95.45% af observationerne?</li>
</ol>
<p>Læg mærke til at 1. og 3. er hinandens “omvendte”. 65.5% af observationerne er mindre end 0.4. 0.4 er større end 65.5% af observationerne.</p>
<ol start="2" type="1">
<li>og 4. er også hinandens omvendte. 95.45% af observationerne ligger mellem -2 og 2. Og hvis vi vil have 95.45% af observationerne finder vi dem i intervallet fra -2 til 2. Hvis intervallet er centreret om midten.</li>
</ol>
<p>I vil ofte blive spurgt om hvad referenceintervallet er - i hvilket interval finder vi 95% af observationerne.</p>
</section>
<section id="hvilke-andre-egenskaber-har-den" class="slide level2">
<h2>Hvilke andre egenskaber har den?</h2>

<img data-src="The_Normal_Distribution.svg" class="r-stretch"></section>
<section id="fine-tal---hvordan-finder-vi-dem-selv" class="slide level2">
<h2>Fine tal - hvordan finder vi dem selv?</h2>
<p>pnorm qnorm dnorm og rnorm findes også - dem har vi sjældent brug for.</p>
<p>pnorm(x) fortæller hvad sandsynligheden p er for at se en observation der er mindre end x.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1586553</code></pre>
</div>
</div>
<p>qnorm(p) fortæller os den værdi x, hvor sandsynligheden for at være mindre end x er p.&nbsp;</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964</code></pre>
</div>
</div>
<p>Eller. pnorm går fra værdi til sandsynlighed. qnorm går fra sandsynlighed til værdi</p>
<p>P(X&lt;0) = 0.4 er den notation vi skal have introduceret</p>
</section>
<section id="forskellige-normalfordelinger" class="slide level2">
<h2>Forskellige normalfordelinger</h2>
<p>For mu og sigma kan være forskellige</p>
</section>
<section id="hvorfor-er-den-vigtig" class="slide level2">
<h2>Hvorfor er den vigtig?</h2>
<aside class="notes">
<p>vi bruger mænds højde som eksempel - fordi vi gennem session - nu forsvarets dag - faktisk er ret tæt på at have data fra hele populationen. Det illustrerer dog også et par andre udfordringer. Mænd med dværgvækst vil typisk blive fritaget fra session da de alligevel vil blive kasseret. Det betyder at vi kommer til at mangle en række målinger der systematisk påvirker gennemsnittet.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<p>Normalfordelingen er særligt vigtig på grund af “Den Centrale Grænseværdisætning”.</p>
<p>Vi er interesseret i gennemsnitshøjden af danske mænd. Vi ved ikke hvilken sandsynlighedsfordeling der beskriver danske mænds højde.</p>
<p>Så vi tager en stikprøve på eksempelvis 20 mænd fra populationen - alle danske mænd - og måler deres højde.</p>
<p>Så beregner vi gennemsnittet og gemmer det.</p>
<p>Det gentager vi mange gange. Ny stikprøve - mål - beregn gennemsnit. Ny stikprøve - mål - beregn gennemsnit.</p>
<p>Det gør vi mange gange. Så vil de gennemsnit, middelværdierne - følge normalfordelingen. <em>Uanset</em> hvilken sandsynlighedsfordeling danske mænds højde følger.</p>
<p>Det kan man føre bevis for. Hvis I kan forstå det bevis, skulle I have læst matematik i stedet for medicin. Så det springer vi over.</p>
</section>
<section id="hvorfor-er-den-vigtig-for-jer" class="slide level2">
<h2>Hvorfor er den vigtig for jer?</h2>
<p>Ret ofte er der en typeopgave der grundlæggende tester om I forstår normalfordelingen.</p>
<p>Og så bruges den i de statistiske tests</p>
</section>
<section id="normaliseringskalering" class="slide level2">
<h2>normalisering/skalering</h2>
<p>Normalfordelingen er normalt standardiseret. Den har middelværdi 0 og standardafvigelse 1.</p>
<p>Det har vores data normalt <em>ikke</em>. Hvad gør vi så?</p>
<p>Vi skalerer vores data. Hvis vi har en række observationer, der har en bestemt middelværdi, og trækker den middelværdi fra alle observationerne - hvad er så den nye middelværdi? 0.</p>
<p>Hvis vi dividerer alle observationerne med sigma - hvad er så den nye standardafvigelse? Den er 1.</p>
<p>Så har vi nu en række observationer med middelværdi 0 og standardafvigelse 1. Det er ikke det samme som at de er normalfordelte</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>se også scale funktionen</p>
<p>forskellen på X-bar og mu</p>
<p>pnorm,dnorm, qnorm</p>
</section>
<section id="logaritmering" class="slide level2">
<h2>Logaritmering</h2>
<p>Ud over skalering af data er der en anden skalering eller transformation vi ofte foretager - logaritmering.</p>
<p>Ting der ikke er normalfordelte bliver det ofte hvis man tager logaritmen til dem.</p>
</section>
<section id="eksamen" class="slide level2">
<h2>Eksamen</h2>
<p>Der er ofte en opgave hvor I får oplyst nogen egenskaber ved en stikprøve.</p>
<p>Ud fra de egenskaber skal I svare på spørgsmål om hvad vi kan fortælle om populationen - eller stikprøven - ud fra disse egenskaber.</p>
</section>
<section id="det-er-en-sandsynlighedsfordeling.-hvad-er-det" class="slide level2">
<h2>Det er en sandsynlighedsfordeling. Hvad er det?</h2>
<p>Når vi undersøger et eller andet der kan have forskellige værdier, viser det sig at disse forskellige værdier optræder med forskellig sandsynlighed. Der er måler der ses oftere end andre. I kommer til at se flere systoliske blodtryk omkring 120 mmHg, end omkring 200 mmHg. (eller… I kommer nok ikke til at se så mange patienter der klager over at have et normalt blodtryk).</p>
<p>De her sandsynligheder kan fordele sig forskelligt, afhængig af hvad der egentlig styrer hvordan værdierne egentlig opstår. Så de kan se forskellige ud:</p>

<img data-src="normalfordelingen_files/figure-revealjs/4-distibutions-1.png" width="480" class="r-stretch"><p>Afhængig af den konkrete fordeling, er det forskellige ting der styrer dens udseende. Det de har til fælles er at arealet under kurven er 1. 1 svarer til 100%. Og når sandsynlighedsfordelingen beskriver sandsynligheden for alle mulige værdier, så er den samlede sandsynlighed 100%</p>
<p>Normalfordelingen styres af værdiernes middelværdi, og deres standardafvigelse.</p>
<p>R har en række funktioner vi kan bruge:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0249979</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3988176</code></pre>
</div>
</div>
<p>Bemærk at vi starter længst ude til venstre. Så pnorm(-2)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02275013</code></pre>
</div>
</div>
<p>fortæller os at 0.02275 eller 2.275% af observationerne er mindre end -2. Og husk at vi på X-aksen har enheder af sd.</p>
<p>Den giver os arealet under kurven fra -uendelig til den værdi vi angiver.</p>
<p>Det betyder også at hvis vi skal have arealet mellem to værdier (eksempelvis -1.96 til 1.96), skal vi beregne hvad arealet fra -uendelig til 1.96 er Og trække arealet fra -uendelig til -1.96 fra:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9500042</code></pre>
</div>
</div>
<p>Med andre ord, 95% af observationerne ligger mellem -1.96 og 1.96.</p>
</section>
<section id="og-hvad-når-mine-data-ikke-har-en-middelværdi-på-0" class="slide level2">
<h2>Og hvad når mine data ikke har en middelværdi på 0?</h2>
<p>Jamen så normerer vi.</p>
<p>Lad os tage nogen mere eller mindre tilfældige tal:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.75</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.64604</code></pre>
</div>
</div>
<p>Så kan vi trække middelværdien fra alle tallene</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Standardafvigelsen er stadig ikke 0:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.64604</code></pre>
</div>
</div>
<p>Men hvis vi dividerer tallene med standardafvigelsen:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.040834e-17</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Så har vi såkaldt normerede værdier, eller skalerede om man vil.</p>
<p>Og deres middelværdi er 0 (eller så tæt på at vi ikke kan se forskel) Og deres standardafvigelse er 1.</p>
<p>Så kan vi bruge pnorm og de andre funktioner. Og når vi skal tilbage til de oprindelige tal - så ganger vi med den oprindelige standardafvigelse, og lægger den oprindelige middelværdi til.</p>
<p>Alternativt bruger vi et trick i pnorm/qnorm:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2840467</code></pre>
</div>
</div>
</section>
<section id="hvordan-gør-man-det-lidt-kortere" class="slide level2">
<h2>Hvordan gør man det lidt kortere?</h2>
<p>Den standardiserede normalfordeling er <span class="math inline">\(N(0, 1)\)</span></p>
<p>Den fordeling vi som regel får er ikke standardiseret, men har formen:</p>
<p><span class="math inline">\(X(\bar{X},s)\)</span> (skal det været et lille x et sted?)</p>
<p>Og vi vil som regel skrive at <span class="math inline">\(X(\bar{X},s) \sim N(\mu, \sigma)\)</span></p>
<p>Altså at vores fordeling X (som er beskrevet af middelværdi og spredning) er ækvivalent med den standardiserede normalfordeling med</p>
<p>Der er en modelløsning der vil være fin her.</p>
<p>og så omregningen…</p>
</section>
<section id="øvelse" class="slide level2">
<h2>Øvelse</h2>
<p>Indtil andet oplyses, taler vi om en standardiseret normalfordeling med mu = 0, og sigma = 1.</p>
<p>Hvilken andel af observationerne er mindre end -3?</p>
<p>hvilken andel af observationerne er større end -3</p>
<p>hvilken andel af observationerne er større end 1.5?</p>
<p>Hvilken andel af observationerne ligger mellem 1 og 1.5?</p>
<p>Hvis vi vil have 47% af observationerne, hvilket interval (centreret om 0) skal vi så have?</p>
</section>
<section id="øvelse-1" class="slide level2">
<h2>Øvelse</h2>
<p>Hvis vi har en population med normalfordelte værdier der har en spredning på <span class="math inline">\(\sigma = 6.52\)</span> og 40% af værdierne er mindre end 0. Hvad er så middelværdien for denne fordeling?</p>
<p>Vi ved ikke hvad middelværdien er. Men vi ved at standardafvigelsen er 6.52.</p>
<p>Så den er ikke normaliseret/skaleret.</p>
<p>vores fordeling kalder vi for X. den er en normalfordeling N(mu, 6.52)</p>
<p>Så det skal nævnes, at notationen er N(mu, sd)</p>
<p>Vi er på jagt efter P(X&lt;0) = 0.4</p>
<p>Det skal vi have normeret/skaleret:</p>
<p>P((X-mu)/6.52 &lt; (0-mu)/6.52) = 0.4</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2533471</code></pre>
</div>
</div>
<p>For at transformere vores værdier, skal vi trække fra, og dividere med standardafvigelsen.</p>
<p>Det gælder også den 0 værdi vi leder efter</p>
<p>(0-mu)/sd</p>
<p>Yderligere øvelser For en population af normalfordelte værdier ved vi at 50% af værdierne er mindre end 0. Og at 60% af værdierne er mindre end 1. Hvad er middelværdi og spredning for den population?</p>
<p>Vi skal tidligere have nævnt medianen og sammenhængen mellem den og gennemsnittet i normalfordelinger</p>
<p>Der skal bruges lidt flere ord på beskrivelsen af fordelingen. altså mere generelt at en fordeling X~N(mu,sigma) kan transformeres til (X-mu)/sigma.</p>
<p>Og så yderligere en række øvelser. Typeopgaverne her er tests af om man forstår normalfordelingen, og kan regne på den.</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../pics/kubdatalab.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>