<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>PUFF SEMS forberedelse – Ting at huske</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link rel="stylesheet" href="webr-custom.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Ting at huske</h1>

<div class="quarto-title-authors">
</div>

</section>
<section class="slide level2">

<p>Forskellen på kategoriske og kontinuærte variable</p>
</section>
<section id="en-eksamensopgave" class="slide level2">
<h2>en eksamensopgave</h2>
<p>Vi har undersøgt koncentrationen af et hormon hos ellers sunde og raske drenge. Vi ønsker at undersøge sammenhængen mellem denne koncentration og drengenes alder og BMI.</p>
<p>Drengene blev opdelt i aldersgrupper, og vi får oplyst hvor mange der var i hver:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (5,8]   (8,9]  (9,10] (10,11] (11,12] (12,13] (13,14] (14,15] (15,16] (16,17] 
    115      44      40      45      43      29      33      38      37      32 
(17,18] (18,20] 
     32      10 </code></pre>
</div>
</div>
<p>Vi får også et eksempel på data fra datasættet:</p>
<p>Vi får nu oplyst at der er foretaget følgende analyse:</p>
<blockquote>
<p>model=lm(horm~factor(Ald.gr)+BMI) summary(model)</p>
</blockquote>
<p>Hvilket giver dette resultat:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 5
   Coefficients          Estimate `Std. Error` `t value` `Pr(&gt;|t|)`  
   &lt;chr&gt;                    &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;       
 1 (Intercept)             5.40         0.368     14.7   &lt;2e-16 ***  
 2 factor(Ald.gr)(8,9]     0.0734       0.202      0.363 0.71700     
 3 factor(Ald.gr)(9,10]    0.357        0.199      1.79  0.07382 .   
 4 factor(Ald.gr)(10,11]   0.579        0.209      2.78  0.00581 **  
 5 factor(Ald.gr)(11,12]   1.09         0.197      5.53  6.42e-08 ***
 6 factor(Ald.gr)(12,13]   1.37         0.221      6.23  1.37e-09 ***
 7 factor(Ald.gr)(13,14]   2.29         0.219     10.5   &lt; 2e-16 *** 
 8 factor(Ald.gr)(14,15]   2.12         0.211     10.0   &lt; 2e-16 *** 
 9 factor(Ald.gr)(15,16]   2.24         0.209     10.7   &lt; 2e-16 *** 
10 factor(Ald.gr)(16,17]   1.71         0.230      7.45  7.30e-13 ***
11 factor(Ald.gr)(17,18]   1.72         0.227      7.61  2.71e-13 ***
12 factor(Ald.gr)(18,20]   1.32         0.321      4.10  5.14e-05 ***
13 BMI                     0.0582       0.0218     2.67  0.00791 **  </code></pre>
</div>
</div>
<ol type="a">
<li>Hvilken analyse er der udført.</li>
</ol>
<p>ud fra “model = lm(osv)” kan vi se at det er en lineær regression. Den er multipel fordi der er mere end en forklarende variabel. Vi har alder som kategorisk forklarende variabel, og BMI som kontinuert forklarende variabel.</p>
<ol start="2" type="a">
<li><p>fortolk resultaterne. vi ser at hormonniveauet tilsyneladende stiger med stigende alder (og fastholdt BMI). Eksempelvis er hormonniveauet for alderskategorien (11,12] 1.08688 højere end for referencen (5,8]. Stigningen er statistisk signifikant for næsten alle aldersgrupper. Der er dog en vis variation i hvor meget hormonniveauet stiger med alderen. BMI er også klart signifikant med en middel stigning i hormonniveuaet på 0.058 pr BMI-point (ved fastholdt alder)</p></li>
<li><p>Prædikter (forudsig) hormonniveauet for en dreng på 6 år med et BMI på 17 og for en dreng på 14 med et BMI på 18.</p></li>
</ol>
<p>Det finder vi ved: Den 6-årige: 5.40 + 0.058*17</p>
<p>for den 14-årige 5.40+0.229+0.058*18</p>
</section>
<section id="opgave" class="slide level2">
<h2>Opgave</h2>
<p>Vi får oplyst data for 18 tilfældigt valgte insulin-afhængige diabetikere. Data er procent af idealvægt. 95 betyder at pågældende individ fjer 5% mindre end idealvægten. 120 beetyder at vedkommende vejer 20% mere end idealvægten.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.42447</code></pre>
</div>
</div>
<p>Vi får oplyst at et 90% reference interval kan beregnes til (89.1; 136.5)</p>
<ol type="a">
<li>Beregn et 95% konfidensinterval for den sande middelprocent af idealvægt.</li>
</ol>
<p>Et referenceinterval er centreret om middelværdien. Så middel finder vi ved: (89.1+136.5)/2 = 112.8</p>
<p>Så skal vi finde spredningen. Det er et 90% interval. så den kvantil der er brugt er ikke 95% kvantilen (1.96), men 90% kvantilen:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.644854</code></pre>
</div>
</div>
<p>0.95 i stedet for 0.975 fordi der skal være 5% på hver side, ikke 2.5%</p>
<p>Intervallet er +/- på hver side af middelværdienm så: 136.5-112.8 = 1.644854*s -&gt; s = (136.5-112.8)/1.644854 = 14.4</p>
<p>Så ved vi hvad standardafvigelsen er på data. Nu skal vi have konfidensintervallet på middelværdien - så vi skal bruge SEM:</p>
<p>14.4/sqrt(18) = 3.394113</p>
<p>Og så finder vi konfidensintervallet ved: 112.8 + c(-1,1)<em>1.96</em>14.4/sqrt(18)</p>
<p>Og her er der altså en regnefejl i modelløsningen…</p>
<ol start="2" type="a">
<li>Indeholder det konfidensinterval vi har beregnet 100%? Hvad fortæller svaret på det spørgsmål? Angiv relevant nullhypotese, samt eventuelt relevant estimat.</li>
</ol>
<p>fra a ser vi at 95% konfidensintervallet ikke indeholder 100 - så vi må afvise nullhypotesen H_0: mu = 100, hvor mu angiver den sande middelprocent af idealvægt for populationen af insulin-afhængige diabeetikere. Estimatet for mu er 112.8 med et 95% KI på det vi tidligere beregnede.</p>
</section>
<section id="opgave-1" class="slide level2">
<h2>opgave</h2>
<p>1473 børn i Guinea-Bissau blev undersøgt for at finde ud af om der, ud over gavnlig effekt af vaccination mod specifikke sygdomme, også var en generelt reduceret børne-dødelighed.</p>
<p>Børnene blev besøgt to gange i deres hjem. Første gang tidligt efter fødslen hvor der blev vaccineret. anden gang ca. 6 måneder senere, hvor der blev fulgt op. En del, men ikke alle børn blev vaccineret med DTP (difteri, tetanus og pertussis).</p>
<p>Variablene i datasættet oplyses at være: alder - alder ved vaccinationen - i år status - status ved opfølgning. 1: død, 0: i live dtp: blev barnet vaccineret. 1: ja, 0: nej vægt;: barnets vægt ved vaccination (i kg) etniskgr: etnisk gruppe 0: Manjaco, Fula, 1: Mandinga og anden</p>
<p>Vi får også oplyst de seks første observationer i datasættet:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  alder status   dtp etngr vaegt
  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.592      0     1     1   5.6
2 0.425      1     1     1   6  
3 0.51       0     1     1   6.2
4 0.592      0     1     1   6.2
5 0.173      0     0     1   5.6
6 0.173      0     0     1   5.2</code></pre>
</div>
</div>
<p>Og optælling: &lt; table(dtp,status)</p>
<p>status dtp 0 1 0 526 9 1 892 46</p>
<ol type="a">
<li>Ser det umiddelbart ud til at der er en sammenhæng mellem dødeligheden og vaccinestatus?</li>
</ol>
<p>Vi har tælletal Hvad er sandsynligheden for død ved dtp lig 0 og 1?</p>
<p>p_0 = 9/(526+9) = 1.7% p_1 = 46/(46+892) = 4.9%</p>
<p>Den relative risiko: RR_1:0 ) 4.9/1.7 = 2.88.</p>
<p>Hvad er det tilhørende 95% konfidens interval?</p>
<p>Log(RR) = 1.06, standardfejlen på log(rr) = sqrt(1/9 + 1/46 - 1/(526+9)-1/(46+892))</p>
<p>DETTE UDLØSER ET HELT NYT SÆT SLIDES og modelløsnignen har tastefejl… exp(1.06 + c(-1,1)<em>1.96</em>0.36). Under alle omstændigheder - 1 - som ville være at der ikke var forskel, er ikke indeholdt. for H_0 er at RR = 1</p>
<ol start="2" type="a">
<li>Hvordan vil vi undersøge sammenhængen mellem dødeligheden og vaccinestatus?, hvor der justeres for de øvrei variable?</li>
</ol>
<p>Det er et binært udfald. Så en logistisk regression. Det gør vi i glm, med family binomial glm(status~vaegt + alder + factor(dtp) + factor(etngr), family = “binomial”)</p>
<p>Den korrekte analyse gav nedenstående resultat:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  Coefficients   Estimate `Std. Error` `t value` `Pr(&gt;|t|)`
  &lt;chr&gt;             &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;     
1 (Intercept)      0.0567      0.0287       1.98 0.048 *   
2 factor(dtp)1     0.0261      0.0116       2.25 0.025 *   
3 factor(etngr)1   0.0229      0.0103       2.22 0.027 *   
4 alder            0.0584      0.0390       1.5  0.134     
5 vaegt           -0.0114      0.00527     -2.16 0.031 *   </code></pre>
</div>
</div>
<p>Fortolk resultatet. Er der sammenhæng mellem vaccinestatus og dødeligheden? Giv et relevant effektmål med tilhørende 95% konfidensinterval</p>
<p>dtp er signifikant, også efter der justeres for etnicitet, alder og vægt, med p = 0.025</p>
<p>OR estimeres til exp(0.026) = 1.026 med et 95% konfidensinterval på: exp(0.026 + c(-1,1)<em>1.96</em>0.012)</p>
</section>
<section id="øvelse" class="slide level2">
<h2>Øvelse</h2>
<p>Vi skal undersøge om type 2 diabetes patienter med bedre glykæmisk kontrol, har et bedre selvvurderet helbred.</p>
<p>Vi har følgende variable</p>
<p>HBAAlC_dik: 1 hvis HbAlc &lt; 9%, 0 hvis HbAlc &gt;= 9% (note til ikke-medicineren. 1 er godt helbred) SRH_dik: 1 hvis selvvurderet helbred er godt/meget godt. 0 hvis det er nogenlunde/dårligt/meget dårligt AGE: Alder i år SEX: Køn. 0: Kvinde, 1: Mand</p>
<p>Vi gør i R følgende og får: &gt;table(SRH_dik, HBAlC_dik)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       HBAlC_dik
SRH_dik   0   1
      0 412 264
      1 354 188</code></pre>
</div>
</div>
<ol type="a">
<li>Baseret på den tabel - er der sammenhæng mellem de to variable?</li>
</ol>
<p>Hvad er den relative risiko for at have godt helbred hvis HbAlc er 1 - altså velreguleret.</p>
<p>Den relative risiko finder vi ved: (188/(188+264))/(354/(354+412)) = 0.900005 pas på paranteserne!</p>
<p>Der er dermed reduceret sandsynlighed for godt selvvurderet helbred hvis man er velreguleret. Er det statistisk signifikant?</p>
<p>Det kræver vi har s.e. for rr sqrt(1/188 - 1/(188+264) + 1/354 - 1/(354+412)) = 0.0680157</p>
<p>deter standardfejlen på log RR exp(log(0.900005) + c(-1,1)<em>1.96</em>0.0680157) Da det omfatter 1, er den reducerede sandsynlighed ikke signifikant.</p>
<p>Man kan også bruge chi^2</p>
<ol start="2" type="a">
<li>Nu udfører vi denne analyse i R: &gt;model1 &lt;- glm(SRH_dik ~ factor(HBAlC_dik)+ factor(SEX) + Age, family = “binomial”) &gt;summary(model1)</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div id="oiyymbpstr" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#oiyymbpstr table {
  font-family: 'Courier Prime', system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#oiyymbpstr thead, #oiyymbpstr tbody, #oiyymbpstr tfoot, #oiyymbpstr tr, #oiyymbpstr td, #oiyymbpstr th {
  border-style: none;
}

#oiyymbpstr p {
  margin: 0;
  padding: 0;
}

#oiyymbpstr .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#oiyymbpstr .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#oiyymbpstr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#oiyymbpstr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#oiyymbpstr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#oiyymbpstr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
}

#oiyymbpstr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#oiyymbpstr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#oiyymbpstr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#oiyymbpstr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#oiyymbpstr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#oiyymbpstr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#oiyymbpstr .gt_spanner_row {
  border-bottom-style: hidden;
}

#oiyymbpstr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#oiyymbpstr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#oiyymbpstr .gt_from_md > :first-child {
  margin-top: 0;
}

#oiyymbpstr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#oiyymbpstr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#oiyymbpstr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#oiyymbpstr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#oiyymbpstr .gt_row_group_first td {
  border-top-width: 0px;
}

#oiyymbpstr .gt_row_group_first th {
  border-top-width: 0px;
}

#oiyymbpstr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#oiyymbpstr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#oiyymbpstr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#oiyymbpstr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#oiyymbpstr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#oiyymbpstr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#oiyymbpstr .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#oiyymbpstr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#oiyymbpstr .gt_table_body {
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
}

#oiyymbpstr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#oiyymbpstr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#oiyymbpstr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#oiyymbpstr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#oiyymbpstr .gt_left {
  text-align: left;
}

#oiyymbpstr .gt_center {
  text-align: center;
}

#oiyymbpstr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#oiyymbpstr .gt_font_normal {
  font-weight: normal;
}

#oiyymbpstr .gt_font_bold {
  font-weight: bold;
}

#oiyymbpstr .gt_font_italic {
  font-style: italic;
}

#oiyymbpstr .gt_super {
  font-size: 65%;
}

#oiyymbpstr .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#oiyymbpstr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#oiyymbpstr .gt_indent_1 {
  text-indent: 5px;
}

#oiyymbpstr .gt_indent_2 {
  text-indent: 10px;
}

#oiyymbpstr .gt_indent_3 {
  text-indent: 15px;
}

#oiyymbpstr .gt_indent_4 {
  text-indent: 20px;
}

#oiyymbpstr .gt_indent_5 {
  text-indent: 25px;
}

#oiyymbpstr .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#oiyymbpstr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="Term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"></th>
<th id="Estimate" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Estimate</th>
<th id="Std.-Error" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Std. Error</th>
<th id="t-value" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">t value</th>
<th id="Pr(>|t|)" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Term">(Intercept)</td>
<td class="gt_row gt_left" headers="Estimate">0.717969</td>
<td class="gt_row gt_left" headers="Std. Error">0.350389</td>
<td class="gt_row gt_left" headers="t value">2.049</td>
<td class="gt_row gt_left" headers="Pr(>|t|)">0.04046*</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Term">factor(HBAlC_dik)1</td>
<td class="gt_row gt_left" headers="Estimate">-0.188731</td>
<td class="gt_row gt_left" headers="Std. Error">0.120637</td>
<td class="gt_row gt_left" headers="t value">-1.564</td>
<td class="gt_row gt_left" headers="Pr(>|t|)">0.11771</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Term">factor(SEX)1</td>
<td class="gt_row gt_left" headers="Estimate">0.252051</td>
<td class="gt_row gt_left" headers="Std. Error">0.117514</td>
<td class="gt_row gt_left" headers="t value">2.145</td>
<td class="gt_row gt_left" headers="Pr(>|t|)">0.03196*</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Term">AGE</td>
<td class="gt_row gt_left" headers="Estimate">-0.015573</td>
<td class="gt_row gt_left" headers="Std. Error">0.005099</td>
<td class="gt_row gt_left" headers="t value">-3.054</td>
<td class="gt_row gt_left" headers="Pr(>|t|)">0.00226**</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Hvad har vi gjort, og hvordan fortolker vi resultaterne?</p>
<p>Vi har gennemført en logistisk regression, med tre forklarende variable, AGE som kontinuert og HBAlC_dik og SEX som kategoriske variabel. Vi ser at HBAlC ikke er signifikant. Både køn og alder er signifikante med tilhørende Odds-ratio på exp(0.252051) = 1.28 for køn, med et 95%KI på exp(0.252051 + c(-1,1)<em>1.96</em>0.117514) Mandlige diabetikere har derfor 28% større odds for godt helbred (selvrapporteret) sammenlignet med kvindelige diabetikere, og et KI på med alder og HBAlC fastholdt.</p>
<p>Alder er også statistisk signifkant med odds ratio på exp(-0.015573) = 0.9845476 diabetikere har derfor ~1.2% reduceret odds for godt helbred (med fastholdt køn og HBAlC) ved en 1 års øgning ialder. KI:</p>
<p>exp(-0.015573 + c(-1,1)<em>1.96</em>0.005099)</p>
<p>Hvis vi ønsker hvad det er for eg 5 år, skal der ganges med 5 på både estimatet og standardfejlen</p>
</section>
<section id="opgave-2---fra-en-eksamen" class="slide level2">
<h2>opgave 2 - fra en eksamen</h2>
<p>Vi ser på data fra ca 1000 patienters risiko for at dø ved en operation (laparotomi). Har øget ilt-tilførsel under operationen betydning for død i en opfølgnigsperiode på ca. 3 år. Patienterne blev randomiseret til et af to ilt-regimer</p>
<p>Vi har følgende variable Allokering: X - patient fik 80% ilt, Y Patient fik 30% ilt diagn_cancer: j: cancer, n: ikke cancer blod: j perioperativ blodtransfusion, n ikke perioperativ blodtransfusion bmi: patientens BMI dead: 1 patienten dør i løbet af opfølgningsperioden, 0 patienten overlever</p>
<p>De første 6 observationer:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Allokering diagn_cancer blod    bmi  dead
  &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Y          n            n      29.3     0
2 X          n            n      28.1     0
3 X          j            n      21.5     1
4 X          j            n      17.3     1
5 Y          n            n      24.2     0
6 Y          n            n      18.2     0</code></pre>
</div>
</div>
<ol type="a">
<li><p>Hvis vi alene betragter patienternes bmi, hvordan ville vi så undersøge om den har signifikant betydning for risikoen for dø efter operation. Outcome - dead er binær og bmi er kontinuært. Så vi vil modellere et kategorisk outcome med kontinært forklarende variabel: logistisk regression</p></li>
<li><p>Når vi gør det, får vi følgende resultat (de fortsætter deres juleleg med at fjerne dele af output):</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div id="piaihvtgwg" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#piaihvtgwg table {
  font-family: 'Courier Prime', system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#piaihvtgwg thead, #piaihvtgwg tbody, #piaihvtgwg tfoot, #piaihvtgwg tr, #piaihvtgwg td, #piaihvtgwg th {
  border-style: none;
}

#piaihvtgwg p {
  margin: 0;
  padding: 0;
}

#piaihvtgwg .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#piaihvtgwg .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#piaihvtgwg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#piaihvtgwg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#piaihvtgwg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#piaihvtgwg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
}

#piaihvtgwg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#piaihvtgwg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#piaihvtgwg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#piaihvtgwg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#piaihvtgwg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#piaihvtgwg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#piaihvtgwg .gt_spanner_row {
  border-bottom-style: hidden;
}

#piaihvtgwg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#piaihvtgwg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#piaihvtgwg .gt_from_md > :first-child {
  margin-top: 0;
}

#piaihvtgwg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#piaihvtgwg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#piaihvtgwg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#piaihvtgwg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#piaihvtgwg .gt_row_group_first td {
  border-top-width: 0px;
}

#piaihvtgwg .gt_row_group_first th {
  border-top-width: 0px;
}

#piaihvtgwg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#piaihvtgwg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#piaihvtgwg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#piaihvtgwg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#piaihvtgwg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#piaihvtgwg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#piaihvtgwg .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#piaihvtgwg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#piaihvtgwg .gt_table_body {
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
}

#piaihvtgwg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#piaihvtgwg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#piaihvtgwg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#piaihvtgwg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#piaihvtgwg .gt_left {
  text-align: left;
}

#piaihvtgwg .gt_center {
  text-align: center;
}

#piaihvtgwg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#piaihvtgwg .gt_font_normal {
  font-weight: normal;
}

#piaihvtgwg .gt_font_bold {
  font-weight: bold;
}

#piaihvtgwg .gt_font_italic {
  font-style: italic;
}

#piaihvtgwg .gt_super {
  font-size: 65%;
}

#piaihvtgwg .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#piaihvtgwg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#piaihvtgwg .gt_indent_1 {
  text-indent: 5px;
}

#piaihvtgwg .gt_indent_2 {
  text-indent: 10px;
}

#piaihvtgwg .gt_indent_3 {
  text-indent: 15px;
}

#piaihvtgwg .gt_indent_4 {
  text-indent: 20px;
}

#piaihvtgwg .gt_indent_5 {
  text-indent: 25px;
}

#piaihvtgwg .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#piaihvtgwg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="Term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"></th>
<th id="Estimate" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Estimate</th>
<th id="Std.-Error" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Std. Error</th>
<th id="z-value" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">z value</th>
<th id="Pr(>|z|)" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Term">(Intercept)</td>
<td class="gt_row gt_left" headers="Estimate">-0.007041</td>
<td class="gt_row gt_left" headers="Std. Error">0.386263</td>
<td class="gt_row gt_left" headers="z value">-0.018</td>
<td class="gt_row gt_left" headers="Pr(>|z|)">0.98546</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Term">bmi</td>
<td class="gt_row gt_left" headers="Estimate"></td>
<td class="gt_row gt_left" headers="Std. Error">0.015385</td>
<td class="gt_row gt_left" headers="z value">-3.151</td>
<td class="gt_row gt_left" headers="Pr(>|z|)"></td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Hvad kan vi sige ud fra det?</p>
<p>Vi mangler et estimat for bmi. Det kan vi beregne, fordi z-value finder vi ved at dividere estimatet med standardfejlen. Derfor kan vi finde estimatet ved at gange standardfejl med z value.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.04847813</code></pre>
</div>
</div>
<p>Teststørrelsen er klart signifikant</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001627125</code></pre>
</div>
</div>
<p>Vi kan beregne OR:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9526782</code></pre>
</div>
</div>
<p>Så holdes alt andet konstant, vil en patient med et bmi der er 1 større end en anden patient, have vil odds for død reduceres med ca 5% for patienten med det højeste bmi.</p>
<p>Vi kan beregne et 95% KI:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9243794 0.9818433</code></pre>
</div>
</div>
<p>1 er ikke indeholdt i intervallet, og forskellen er derfor signifkant. Det så vi også fra p-værdien vi beregnede tidligere.</p>
<ol start="3" type="a">
<li>Nu ser vi bort fra bmi, og betrager ilt-allokering.</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Allokering
dead   X   Y
   0 414 418
   1 139 107</code></pre>
</div>
</div>
<p>Hvad kan vi konkludere ud fra det?</p>
<p>Vi sammenligner død (1) for de to ilt-regimer X og Y: odds_X = 139/414 = 0.3357488 P_y = 107/418 = 0.2559809</p>
<p>OR (X mod Y) = 0.3357488/0.2559809 = 1.311617 dvs at odds for at dø estimeres at være ca. 31% højere ved det høje ilt-regime, sammenlignet med det lave (alt andet fastholdt)</p>
<p>95% KI: standardfejlen på log(OR): sqrt(1/139 + 1/414 + 1/107 + 1/418) = 0.146109</p>
<p>exp(log(1.311617) + c(-1,1)<em>1.96</em>0.146109)</p>
<p>Det indeholder 1 og estimatet er derfor ikke statistisk signifikant (de er dog i modelbesvarelser glade for at nævne at det er tæt på at være signifikant)</p>
<p>BETON FORSKEL PÅ OR OG RR!</p>
<ol start="4" type="a">
<li>Tabellen deles nu op efter den opererede patients diagnose (cancer, ja,nej):</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>, , diagn_cancer = j

    Allokering
dead   X   Y
   0 188 213
   1 101  74

, , diagn_cancer = n

    Allokering
dead   X   Y
   0 226 205
   1  38  33</code></pre>
</div>
</div>
<p>Giver det anledning til at ændre den tidligere konklusion? Begnd med effektestimater og 95% konfidensintervaller.</p>
<p>Samme øvelse som før, men nu på hver gruppe: Cancerpatienter: OR = (101/188) / (74/213) = 1.546363 s.e. på log(OR): sqrt(1/101 + 1/188 + 1/74 + 1/213) = 0.1828346 KI: exp(log(1.546363) + c(-1,1)<em>1.96</em>0.1828346) = 1.080636 2.212806</p>
<p>Så for cancerpatienter er odds for at dø ved det høje ilt regime ca 55% højere, med et KI som angivet. Signifikant, da 1 ikke er med i KI.</p>
<p>non-cancer-patienter:</p>
<p>OR = (38/226) / (33/205) = 1.044516 se på log(OR) = sqrt(1/38 + 1/226 + 1/33 + 1/205) = 0.2567521 KI: exp(log(1.044516) + c(-1,1)<em>1.96</em> 0.2567521) = 0.6314854 1.7276943 Så odds er 1.04 gange større i det høje ilt-regime for ikke-cancerpatienter. Men det er ikke signifikant - for 1 er indeholdt i KI.</p>
<p>Så ilt-regime har betydning for cancerpatienter.</p>
</section>
<section id="leversygdomseksamensopgave" class="slide level2">
<h2>leversygdomseksamensopgave</h2>
<p>Vi har data fra 583 personer, der er blevet henvist til undersøgelse pga mistanke om leversygdom. De første 6 observationer er:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
    age albumin ratio globulin status  idnr sex   l_ratio
  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;
1    65     3.3  0.9      3.67      1     1 F      -0.105
2    62     3.2  0.74     4.32      1     2 M      -0.301
3    62     3.3  0.89     3.71      1     3 M      -0.117
4    58     3.4  1        3.4       1     4 M       0    
5    72     2.4  0.4      6         1     5 M      -0.916
6    46     4.4  1.3      3.38      1     6 M       0.262</code></pre>
</div>
</div>
<p>Variable: idnr: Løbenummer sex: Køn age: alder i år status: leversygdom, 1=ja albumin: serum albumin g/dL globulin: serum globulin g/dL ratio: ratio m. albumin og globulin l_ratio: log(ratio) (den naturlige logaritme)</p>
<p>Vi får denne tabel:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      sex
status   F   M
     0  50 117
     1  92 324</code></pre>
</div>
</div>
<p>Og opyst at log-ratio er normalfordelt.</p>
<p>For status = 0 får vi:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Gennemsnit</th>
<th>Spredning (sd)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>l_ratio</td>
<td>-0.011</td>
<td>0.289</td>
</tr>
<tr class="even">
<td>age</td>
<td>41.2</td>
<td>17.0</td>
</tr>
</tbody>
</table>
<p>og for status = 1</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Gennemsnit</th>
<th>Spredning (sd)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>l_ratio</td>
<td>-0.152</td>
<td>0.358</td>
</tr>
<tr class="even">
<td>age</td>
<td>46.2</td>
<td>15.7</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>er der forskel i log-ratio mellem syge og raske, når der ikke tages højde for forskell i alder og køn.</li>
</ol>
<p>Vi skal bestemme ki for log-ratio mellem syge og raske. Det skal vi bruge SEM til. Raske der er 50+117 = 167, SEM = 0.289/sqrt(167) = 0.02236349 for syge: 92+324 = 416, SEM = 0.358/sqrt(416) = 0.01755239</p>
<p>den poolede sem er derfor: sqrt( 0.02236349^2 + 0.01755239^2) = 0.02842907</p>
<p>Vi skal se om forskellen er 0. forskellen observerer vi til: -0.152 - -0.011 = -0.141 Det giver en teststørrelse på: -0.141/0.02842907 = -4.96</p>
<p>det er klart signifikant (den er næsten fem standardafvigelser fra 0). der er en signifikant lavere l_ratio blandt de syge.</p>
<ol start="2" type="a">
<li>undersøg om kønsfordelingen er den samme for de syge og de raske. Sandsynligheden for at være kvinde blandt de raske: p0 = 50/(50+117) = 0.2994012 Sandsynligheden for at være kvinde blandt de syge: p1 = 92/(92+324) = 0.2211538</li>
</ol>
<p>Hvordan beregnes standardfejlen på det?</p>
<p>s.e. for en andel finder vi ved sqrt(p(1-p)/n)</p>
<p>så se_0 = sqrt(0.2994012<em>(1-0.2994012)/(50+117)) = 0.03544078 og se_1 = sqrt(0.2211538</em>(1-0.2211538)/(92+324)) = 0.02034822</p>
<p>Er den sande værdi af forskellen på de to andele (af kvinder i hhv syg og rask-grupperne) i virkeligheden 0?</p>
<p>Vi ved ikke om spredningen er ens i de to grupper. Så vi skal bruge den poolede se.: se_p = sqrt(0.03544078^2+ 0.02034822^2) = 0.04086684</p>
<p>forskellen er: 0.2994012-0.2211538 = 0.0782474</p>
<p>og den ligger så: 0.0782474/0.04086684 = 1.914692 standardfejl fra 0. Og det er ikke signifikant - fordi det er mindre end 1.96.</p>
<ol start="3" type="a">
<li>Er aldersfordelingen den samme for syge som for raske? Hvordan vil vi undersøge det?</li>
</ol>
<p>two-sample t-test. så er forskellen på gennemsnitlig alder forskellig fra 0? Her nævnte eksamensspørgsmålet specifikt at man blot skulle forklare hvad man ville gøre - man skulle ikke regne.</p>
<ol start="4" type="a">
<li>Nu laver vi denne analyse i R, hvor vi inddrager alder og køn: &gt; analyse1 &lt;- lm(l_ratio~factor(status)+factor(sex)+age) &gt; summary(analyse1)</li>
</ol>
<p>Det gav dette output:</p>
<div class="cell">
<div class="cell-output-display">
<div id="zdpidrcstk" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#zdpidrcstk table {
  font-family: 'Courier Prime', system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#zdpidrcstk thead, #zdpidrcstk tbody, #zdpidrcstk tfoot, #zdpidrcstk tr, #zdpidrcstk td, #zdpidrcstk th {
  border-style: none;
}

#zdpidrcstk p {
  margin: 0;
  padding: 0;
}

#zdpidrcstk .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zdpidrcstk .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#zdpidrcstk .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zdpidrcstk .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zdpidrcstk .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zdpidrcstk .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
}

#zdpidrcstk .gt_col_headings {
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zdpidrcstk .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zdpidrcstk .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zdpidrcstk .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zdpidrcstk .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zdpidrcstk .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zdpidrcstk .gt_spanner_row {
  border-bottom-style: hidden;
}

#zdpidrcstk .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#zdpidrcstk .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zdpidrcstk .gt_from_md > :first-child {
  margin-top: 0;
}

#zdpidrcstk .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zdpidrcstk .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zdpidrcstk .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#zdpidrcstk .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#zdpidrcstk .gt_row_group_first td {
  border-top-width: 0px;
}

#zdpidrcstk .gt_row_group_first th {
  border-top-width: 0px;
}

#zdpidrcstk .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zdpidrcstk .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#zdpidrcstk .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#zdpidrcstk .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zdpidrcstk .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zdpidrcstk .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zdpidrcstk .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#zdpidrcstk .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zdpidrcstk .gt_table_body {
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
}

#zdpidrcstk .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zdpidrcstk .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zdpidrcstk .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zdpidrcstk .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zdpidrcstk .gt_left {
  text-align: left;
}

#zdpidrcstk .gt_center {
  text-align: center;
}

#zdpidrcstk .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zdpidrcstk .gt_font_normal {
  font-weight: normal;
}

#zdpidrcstk .gt_font_bold {
  font-weight: bold;
}

#zdpidrcstk .gt_font_italic {
  font-style: italic;
}

#zdpidrcstk .gt_super {
  font-size: 65%;
}

#zdpidrcstk .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#zdpidrcstk .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#zdpidrcstk .gt_indent_1 {
  text-indent: 5px;
}

#zdpidrcstk .gt_indent_2 {
  text-indent: 10px;
}

#zdpidrcstk .gt_indent_3 {
  text-indent: 15px;
}

#zdpidrcstk .gt_indent_4 {
  text-indent: 20px;
}

#zdpidrcstk .gt_indent_5 {
  text-indent: 25px;
}

#zdpidrcstk .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#zdpidrcstk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="Term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"></th>
<th id="Estimate" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Estimate</th>
<th id="Std.-Error" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Std. Error</th>
<th id="t-value" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">t value</th>
<th id="Pr(>|t|)" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Term">(Intercept)</td>
<td class="gt_row gt_left" headers="Estimate">0.1730998</td>
<td class="gt_row gt_left" headers="Std. Error">0.0488724</td>
<td class="gt_row gt_left" headers="t value">3.542</td>
<td class="gt_row gt_left" headers="Pr(>|t|)">0.000430***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Term">factor(status)1</td>
<td class="gt_row gt_left" headers="Estimate">-0.1196883</td>
<td class="gt_row gt_left" headers="Std. Error">0.0310025</td>
<td class="gt_row gt_left" headers="t value">-3.861</td>
<td class="gt_row gt_left" headers="Pr(>|t|)">0.000126***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Term">factor(sex)M</td>
<td class="gt_row gt_left" headers="Estimate">0.0042939</td>
<td class="gt_row gt_left" headers="Std. Error">0.0324442</td>
<td class="gt_row gt_left" headers="t value">0.132</td>
<td class="gt_row gt_left" headers="Pr(>|t|)">0.894756</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Term">age</td>
<td class="gt_row gt_left" headers="Estimate">-0.0045177</td>
<td class="gt_row gt_left" headers="Std. Error">0.0008616</td>
<td class="gt_row gt_left" headers="t value">-5.241</td>
<td class="gt_row gt_left" headers="Pr(>|t|)">2.24e-7***</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Hvilken analyse er der tale om, og hvad kan vi konkludere på baggrund af den? Fortolk værdier i søjlen “Estimate” svarende til variablene status og age.</p>
<p>Det er en multipel lineær regression med l_ratio som responsvariabel og status, sex og age som forklarende variable. age er kontinuer, status og sex er kategoriske (det ser vi bladnt andet af “factor”). Syge har i gennemsnit, alt andet lige, en signifikant lavere l_ratio end raske. Den estimerer vi til at være ca. 0.12 lavere, jsuteret for køn og alder. Den tilhørende p-værdi er 0.0001 og derfor signifikant. Alderseffekten er også signifikant (p&lt;0.001), og l_ratio falder, i gennemsnit, med 0.0045 pr år. Justeret for status og køn.</p>
<ol start="5" type="a">
<li>predikter median-ratio for de syge i studiepopulationen med en alder på 50 år, som er kvinder.</li>
</ol>
<p>middelværdien kan vie beregne ved: 0.1730998+-0.1196883+50*-0.0045177 = -0.17 Vi har fået oplyst at l_ratio er normalfordelt. I så fald er median og middel ens, så det er medianen vi har fundet. Der efterspørges ratio, ikke l_ratio, så vi skal beregne exp(-0.17) = 0.8436648</p>
<ol start="6" type="a">
<li>Hvordan ville vi undersøge om alder, køn og l_ratio er signifikante prædiktorer for sygdomsstatus? Angiv relevant R-kode</li>
</ol>
<p>Sygdomsstatus er en kategorisk, binær variabel. Så vi ville lave en logistisk regression: glm(status~age+factor(sex1)+l_ratio, family=“binomial”).</p>
<p>Og så ville vi se om p-værdierne var tilstrækkeligt små til at vi kan konkludere at de er signifikante.</p>
</section>
<section id="endnu-en-eksamensopgave" class="slide level2">
<h2>endnu en eksamensopgave</h2>
<p>Vi skal se på prævalensen af tuberkulose blandt stiknarkomaner og om den er afhængig af om der deles sprøjter med andre narkomaner. I en gruppe er 97 narkomaner der deler sprøjte med andre narkomaner, testede 24.7% positiv for TB, mens der i en gruppe på 161 narkomaner der ikke delte sprøjte, var 17.4% der testede positive for TB.</p>
<p>1a) Hvis vi antager at prævalensen af TB for stiknarkomaner ikke afhænger af om man deler sprøjte eller ej, hvad vil vi estimere en proportion til at være? Angiv også et 95% KI for det estimat.</p>
<p>Antal positive: 0.247<em>97 + 0.174</em>161 = (ca) 52 Total i stikprøven: 97+161 = 258 Prævalens: 52/258 = 0.2015504 se på det estimat: sqrt(0.2015504*(1-0.2015504)/258) = 0.02497501</p>
<p>95% KI: 0.2015504 + c(-1,1)<em>1.96</em>0.02497501 = 0.1525994 0.2505014</p>
<p>1b) Undersøg hypotesen om at risikoen for at få TB for stiknarkomaner ikek afhænger af om man deler sprøjte eller ej. Argumenter ud fra relevant KI, eller brug statistisk test. Hvis I kigger på modelbesvarelser for denne opgave - bemærk at der er en regnefejl, hvor der byttes om på n for de to grupper.</p>
<p>KI-tilgangen:</p>
<p>deler: prævalens: 0.247 n = 97 se_deler = sqrt(0.247*(1-0.247)/97) = 0.0437885</p>
<p>deler_ikke: prævalens: 0.174, n = 161 se_deler_ikke: sqrt(0.174*(1-0.174)/161) = 0.02987801</p>
<p>KI_deler 0.247 + c(-1,1)<em>1.96</em>0.0437885 = 0.1611745 0.3328255 KI_deler_ikke: 0.174+c(-1,1)<em>1.96</em>0.02987801 = 0.1154391 0.2325609</p>
<p>Vi bemærker at prævalensen for “deler ikke” er indeholdt i KI_deler, og vi kan derfor konkludere at der ikke er en signifikant forskel.</p>
<p>Alternatit: Forskel i prævalens: 0.247-0.174 = 0.073 SE_diff = sqrt(se_deler^2 + se_deler_ikke^2) = sqrt( 0.0437885^2 + 0.02987801^2) = 0.05301064</p>
<p>teststørrelsen finder vi så ved: 0.073/0.05301064 = 1.377082, der ikke er signifikant (&lt;1.96)</p>
</section>
<section id="eksamen-opgave-2" class="slide level2">
<h2>eksamen opgave 2</h2>
<p>583 personer er henvist til undersøgelse pga mistanke om leversygdom De første seks observationer:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
    age albumin ratio globulin status  idnr sex   l_ratio
  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;
1    65     3.3  0.9      3.67      1     1 F      -0.105
2    62     3.2  0.74     4.32      1     2 M      -0.301
3    62     3.3  0.89     3.71      1     3 M      -0.117
4    58     3.4  1        3.4       1     4 M       0    
5    72     2.4  0.4      6         1     5 M      -0.916
6    46     4.4  1.3      3.38      1     6 M       0.262</code></pre>
</div>
</div>
<p>Variable: idnr: Løbenummer sex: Køn age: alder i år status: leversygdom, 1=ja albumin: serum albumin g/dL globulin: serum globulin g/dL ratio: ratio m. albumin og globulin l_ratio: log(ratio) (den naturlige logaritme)</p>
<p>Der defineres en binær variabel AG.positiv som ratio &lt; 1.1 Det gier os denne tabel:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          status
AG.positiv   0   1
         0  66 106
         1  99 308</code></pre>
</div>
</div>
<ol type="a">
<li>Undesøg om der er en statistisk signifikant sammenhæng mellem de to variable.</li>
</ol>
<p>Her kører vi en chi^2 test:</p>
<p>input:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  input
X-squared = 11.709, df = 1, p-value = 0.0006219</code></pre>
</div>
</div>
<p>Det giver en teststørrelse på 11.7. Vi sætter correct = FALSE fordi de forventede værdier i tabellen er “store”, som i større end 5.</p>
<p>Det svarer til en p-værdi der er &lt;0.001. Så der er signifikant forskel. modelbesvarlsaer bruger ofte formuleringen “klart signifikant”. teknisk set er der ikke noget der er mere signifikant end andet. det er signifikant på et bestemt niveua. Eller også er det ikke. Det er ikke “næsten” eller “meget” signifikant.</p>
<ol start="2" type="a">
<li>Nu udfører vi følgende analyse i R: &gt; model &lt;- glm(status~factor(AG.positiv)+factor(sex)+age, binomial) &gt; summary(model)</li>
</ol>
<p>Den giver dette resultat:</p>
<div class="cell">
<div class="cell-output-display">
<div id="vdyrlstwxf" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#vdyrlstwxf table {
  font-family: 'Courier Prime', system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#vdyrlstwxf thead, #vdyrlstwxf tbody, #vdyrlstwxf tfoot, #vdyrlstwxf tr, #vdyrlstwxf td, #vdyrlstwxf th {
  border-style: none;
}

#vdyrlstwxf p {
  margin: 0;
  padding: 0;
}

#vdyrlstwxf .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#vdyrlstwxf .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#vdyrlstwxf .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#vdyrlstwxf .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#vdyrlstwxf .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vdyrlstwxf .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
}

#vdyrlstwxf .gt_col_headings {
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vdyrlstwxf .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#vdyrlstwxf .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#vdyrlstwxf .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#vdyrlstwxf .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#vdyrlstwxf .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#vdyrlstwxf .gt_spanner_row {
  border-bottom-style: hidden;
}

#vdyrlstwxf .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#vdyrlstwxf .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#vdyrlstwxf .gt_from_md > :first-child {
  margin-top: 0;
}

#vdyrlstwxf .gt_from_md > :last-child {
  margin-bottom: 0;
}

#vdyrlstwxf .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#vdyrlstwxf .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#vdyrlstwxf .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#vdyrlstwxf .gt_row_group_first td {
  border-top-width: 0px;
}

#vdyrlstwxf .gt_row_group_first th {
  border-top-width: 0px;
}

#vdyrlstwxf .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vdyrlstwxf .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#vdyrlstwxf .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#vdyrlstwxf .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vdyrlstwxf .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vdyrlstwxf .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#vdyrlstwxf .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#vdyrlstwxf .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#vdyrlstwxf .gt_table_body {
  border-top-style: solid;
  border-top-width: 0px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 0px;
  border-bottom-color: #D3D3D3;
}

#vdyrlstwxf .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vdyrlstwxf .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vdyrlstwxf .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vdyrlstwxf .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vdyrlstwxf .gt_left {
  text-align: left;
}

#vdyrlstwxf .gt_center {
  text-align: center;
}

#vdyrlstwxf .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#vdyrlstwxf .gt_font_normal {
  font-weight: normal;
}

#vdyrlstwxf .gt_font_bold {
  font-weight: bold;
}

#vdyrlstwxf .gt_font_italic {
  font-style: italic;
}

#vdyrlstwxf .gt_super {
  font-size: 65%;
}

#vdyrlstwxf .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#vdyrlstwxf .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#vdyrlstwxf .gt_indent_1 {
  text-indent: 5px;
}

#vdyrlstwxf .gt_indent_2 {
  text-indent: 10px;
}

#vdyrlstwxf .gt_indent_3 {
  text-indent: 15px;
}

#vdyrlstwxf .gt_indent_4 {
  text-indent: 20px;
}

#vdyrlstwxf .gt_indent_5 {
  text-indent: 25px;
}

#vdyrlstwxf .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#vdyrlstwxf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="Term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"></th>
<th id="Estimate" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Estimate</th>
<th id="Std.-Error" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Std. Error</th>
<th id="z-value" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">z value</th>
<th id="Pr(>|z|)" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Term">(Intercept)</td>
<td class="gt_row gt_left" headers="Estimate">-0.446661</td>
<td class="gt_row gt_left" headers="Std. Error">0.320769</td>
<td class="gt_row gt_left" headers="z value">-1.392</td>
<td class="gt_row gt_left" headers="Pr(>|z|)">0.16378</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Term">factor(AG.postiv)1</td>
<td class="gt_row gt_left" headers="Estimate">0.594643</td>
<td class="gt_row gt_left" headers="Std. Error">0.199556</td>
<td class="gt_row gt_left" headers="z value">2.980</td>
<td class="gt_row gt_left" headers="Pr(>|z|)">0.00288**</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Term">factor(sex)M</td>
<td class="gt_row gt_left" headers="Estimate">0.407717</td>
<td class="gt_row gt_left" headers="Std. Error">0.211941</td>
<td class="gt_row gt_left" headers="z value">1.924</td>
<td class="gt_row gt_left" headers="Pr(>|z|)">0.05439.</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Term">age</td>
<td class="gt_row gt_left" headers="Estimate">0.015131</td>
<td class="gt_row gt_left" headers="Std. Error">0.005927</td>
<td class="gt_row gt_left" headers="z value">2.553</td>
<td class="gt_row gt_left" headers="Pr(>|z|)">0.01069*</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Hvilken analyse er der tale om, og hvad kan vi konkludere på baggrund af det? Angiv relevant størrelse der kvantificerer effekten af AG.positiv. beregn tilhørende 95% KI.</p>
<p>Det er en logistisk regression med status som responsvariabel og AG.positiv og køn som kategoriske forklarende variable, og alder som kontinuær forklarende variabel. Alder og AG.positiv er signifikante i denne justerede analyse, kønnet er ikke.</p>
<p>OR for AG.positiv exp(0.594643) = 1.812384 og vi estimerer derfor at odds for at status er 1 (at man er syg) er en faktor 1.8 større hvis AG.positive patienter, sammenlignet med AG.negative. KI: exp(0.594643 + c(-1,1)<em>1.96</em>0.199556) Da det ikke indeholder 1, er resultatet signifikant (i overensstemmelse med hvad vi så fra p-værdien)</p>
<ol start="3" type="a">
<li>Prædikter sandsynlighednen for at have status 1 (syg) for en AG.positiv kvinde på 50.</li>
</ol>
<p>Vi beregner: -0.446661 + 0.594643 + 50*0.015131 = 0.904532</p>
<p>Det er logodds. Så vi finder sandsynligheden ved: odds er så: exp(0.904532) = 2.470775 Og sandsynligheden finder vi ved: odds/(1+odds) = 2.470775/(1+2.470775) = 0.7118799</p>
</section>
<section id="eksamensopgave---det-er-nok-sem" class="slide level2">
<h2>Eksamensopgave - det er nok SEM</h2>
<p>Vi antager at fødselsvægten for børn født indenfor termin med gestationsalder 40 uger er approksimativt normalfordelt med middelværdi 3500 gram og spredning 430 gram. Vi kan antage at der er tale om populationsværdier. Vi ønsker at undersøge om fødselsvægten for børn hvis mødre røg gennem hele graviditeten har samme middelværdi (<span class="math inline">\(\mu\)</span>). Antag at der indsamles n observationre af fødselsvægten af børn af mødre der røg under hele graviditeten. Hvilken test ville vi anvende for at undersøge om <span class="math inline">\(\mu\)</span> = 3500? Angiv konkret teststørrelse beregnet baseret på de n observationer.</p>
<p>Vi vil skulle beregne SEM for disse børn (sd/n), og dernæst teststørrelse: (X-3500)/SEM.</p>
<ol start="2" type="a">
<li>Hvis den sande <span class="math inline">\(\mu\)</span> er under 3200 gram (eller over 3800 gram), og vi kun vil acceptere en 10% risiko for ikke at opdage en sådan forskel på de to middelværdier, hvor stor en stikprøve skal der så anvendes, med et signifikans niveau på 5%.</li>
</ol>
<p>Samplesize beregning for tosidet test af en middelværdi.</p>
<p>H_0; mu = 3500 H_A mu != 3500 ønsket afvigelse vi skal kunne opdage: delta = 300 = 3800-3500 den er tilsvarende ned til 3200 gram.</p>
<p>risikoen for ikke at opdage den må være på 10%. Det svarer til en power på 90% eller 0.9 alpha = 0.05 beta = 0.1 sigma 430 delta 300</p>
<p>(( qnorm(1-(0.05/2)) + qnorm(1-0.1))*430 / 300)^2 oprundet 22. MEN HVORDAN FINDER MAN UD AF AT DET ER DEN FORMEL DER SKAL BRUGES?</p>
<ol start="3" type="a">
<li>Hvis man beslutter sig for en stikprøve på 100, hvor stor en forskel på mu og 3500 kan vi forvente at kunne finde - hvis vi bruger de samme forudsætninger? Samme formel - men isoler størrelsen - delta i stedet (indsæt 100)</li>
</ol>
<p>(1.96+1.28)*430/delta = 100^2 Så vi kan forvente at opdage forskelle på 139 gram (eller over) med en sandsynlighed på 90%.</p>
</section>
<section id="eksamensopgave-2" class="slide level2">
<h2>Eksamensopgave 2</h2>
<p>Vi skal se på et randomiseret klinisk studie udført på seks forskellige europæiske hospitaler. 349 patienter med leversygdom blev randomiseret til enten den eksperimentelle behadnling UDC (176 patienter) eller placebo (173 patienter)</p>
<p>Udfaldet “failure of medical treatment” blev defineret som enten død eller levertransplantation i den 6 årige undersgelsesperiode. Pateienter blev fulgt fra randomiseringstidspunktet til ovenstående udfald - eller til de 6 år var gået.</p>
<p>Vi får de første 6t observationer i sættet. Y er udfaldsvariablen (1 “treatment failure”), R angiver behandling (1 = UDC), X den standardiserede version af logaritmen af bilirubin (umol/L), målt for hver patient ved starten af studiet</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
      Y     R      X
  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1     1     1  1.62 
2     0     1  1.99 
3     0     1 -0.849
4     1     1  1.50 
5     0     1  1.34 
6     0     1 -0.562</code></pre>
</div>
</div>
<blockquote>
<p>table(Y,R) giver:</p>
</blockquote>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   R
Y     0   1
  0 118 134
  1  55  42</code></pre>
</div>
</div>
<ol type="a">
<li>baseret på ovenstående table ønske beregnet relativ risiko (med tilhørende 95% KI ) til belysning af effekten af behandlingen på det betragtede udfald. Husk at konkludere.</li>
</ol>
<p>Risiko ved behandling: 42/(134+42)= 0.2386364</p>
<p>Risiko ved placebo: 55/(118+55) = 0.3179191</p>
<p>RR = 0.2386364/0.3179191 = 0.7506199</p>
<p>log(RR) = log(0.7506199) = -0.2868559</p>
<p>se.(log(rr)) = sqrt(1/42-1/176+1/55-1/173) = 0.174726</p>
<p>et 95% ki for log(rr) findes til; -0.2868559 + c(-1,1)<em>1.96</em>0.174726 = -0.62931886 0.05560706</p>
<p>Derfor er 95% ki for RR: exp(c(-0.62931886, 0.05560706)) = 0.5329547 1.0571822</p>
<p>RR er 0.75. Så vi estimerer at behandlingen reducerer treatment failure med 25% med et 95% KI på 0.5329547 1.0571822 Da 1 er indeholdt i KI er der dermed ikke tale om en signifikant effekt.</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="kubdatalab.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>